src/Entity/Hobby.php
<?php

namespace App\Entity;

use App\Repository\HobbyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: HobbyRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Hobby
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $hangeul_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone_nb = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gps_coordinates = null;

    #[ORM\ManyToMany(targetEntity: HobbyCategory::class, inversedBy: 'hobbies')]
    private Collection $hobbyCategories;

    #[ORM\ManyToMany(targetEntity: Users::class, mappedBy: 'hobbies')]
    private Collection $users;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $schedule = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $frequency = null;

    #[ORM\Column(nullable: true)]
    private ?int $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $priceFor = null;

    #[ORM\OneToMany(mappedBy: 'hobby', targetEntity: HobbyAdditionalInfo::class, cascade: ["persist"], orphanRemoval: true)]
    private Collection $additionalInfo;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[Vich\UploadableField(mapping: 'hobby_images', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->hobbyCategories = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->additionalInfo = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHangeulName(): ?string
    {
        return $this->hangeul_name;
    }

    public function setHangeulName(?string $hangeul_name): self
    {
        $this->hangeul_name = $hangeul_name;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getPhoneNb(): ?string
    {
        return $this->phone_nb;
    }

    public function setPhoneNb(?string $phone_nb): self
    {
        $this->phone_nb = $phone_nb;

        return $this;
    }

    public function getGpsCoordinates(): ?string
    {
        return $this->gps_coordinates;
    }

    public function setGpsCoordinates(?string $gps_coordinates): self
    {
        $this->gps_coordinates = $gps_coordinates;

        return $this;
    }

    /**
     * @return Collection<int, HobbyCategory>
     */
    public function getHobbyCategories(): Collection
    {
        return $this->hobbyCategories;
    }

    public function addHobbyCategory(HobbyCategory $hobbyCategory): self
    {
        if (!$this->hobbyCategories->contains($hobbyCategory)) {
            $this->hobbyCategories->add($hobbyCategory);
            $hobbyCategory->addHobby($this);
        }

        return $this;
    }

    public function removeHobbyCategory(HobbyCategory $hobbyCategory): self
    {
        if ($this->hobbyCategories->removeElement($hobbyCategory)) {
            $hobbyCategory->removeHobby($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addHobby($this);
        }

        return $this;
    }

    public function removeUser(Users $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeHobby($this);
        }

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getFrequency(): ?string
    {
        return $this->frequency;
    }

    public function setFrequency(string $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceFor(): ?string
    {
        return $this->priceFor;
    }

    public function setPriceFor(string $priceFor): self
    {
        $this->priceFor = $priceFor;

        return $this;
    }

    /**
     * @return Collection<int, HobbyAdditionalInfo>
     */
    public function getAdditionalInfo(): Collection
    {
        return $this->additionalInfo;
    }

    public function addAdditionalInfo(HobbyAdditionalInfo $additionalInfo): self
    {
        if (!$this->additionalInfo->contains($additionalInfo)) {
            $this->additionalInfo->add($additionalInfo);
            $additionalInfo->setHobby($this);
        }

        return $this;
    }

    public function removeAdditionalInfo(HobbyAdditionalInfo $additionalInfo): self
    {
        if ($this->additionalInfo->removeElement($additionalInfo)) {
            // set the owning side to null (unless already changed)
            if ($additionalInfo->getHobby() === $this) {
                $additionalInfo->setHobby(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }
}

templates/hobby/_hobbyCard.html.twig
{% if hobby.imageName %}
    <div class="hobby_card_background" style="background-image: url('{{ vich_uploader_asset(hobby, 'imageFile') | imagine_filter('hobby_card_background') }}');">
{% else %}
    <div class="hobby_card_background">
{% endif %}
    <div class="hobby_card">
        <div class="hobby_card_top">
            <div class="hobby_card_top_left">
                <div class="hobby_card_titles">
                    <div class="hobby_card_title">
                        {{ hobby.name }}
                    </div>
                    <div class="hobby_card_hangeul">
                        {{ hobby.hangeulName }}
                    </div>
                </div>
                <div class="hobby_card_phone">
                    <i class="fa fa-phone"></i> {{ hobby.phoneNb }}
                </div>
            </div>
            <!-- additional information generated through database -->
            <div class="hobby_card_top_right">
                <div class="hobby_card_add_info">
                    {% for additional_info in hobby.additionalInfo %}
                        <div class="hobby_card_add_info_button">
                            {{ additional_info }}
                        </div>
                    {% endfor %}
                </div>
                <div class="hobby_card_basic_info">
                    {% if hobby.schedule %}
                        <div class="hobby_card_basic_info_button">
                            <div class="hobby_card_basic_info_button_main_text">
                                {{ hobby.schedule }}
                            </div>
                            <div class="hobby_card_basic_info_button_sub_text">
                                {{ hobby.frequency }}
                            </div>
                        </div>
                    {% endif %}
                    {% if hobby.price %}
                        <div class="hobby_card_basic_info_button">
                            <div class="hobby_card_basic_info_button_main_text">
                                {{ hobby.price|format_currency('KRW') }}
                            </div>
                            <div class="hobby_card_basic_info_button_sub_text">
                                {{ hobby.priceFor }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="hobby_card_basic_info_button">
                        <div class="hobby_card_basic_info_button_main_text">
                            0.5 kms
                        </div>
                        <div class="hobby_card_basic_info_button_sub_text">
                            10 min walk
                        </div>
                    </div>
                </div>

                {% if app.user %}

                    {% set isFavorite = false %}

                    {% for favorite in app.user.hobbies %}
                        {% if hobby == favorite %}
                            {% set isFavorite = true %}
                        {% endif %}
                    {% endfor %}

                    {% if isFavorite == true %}
                        <form   action="{{ path('app_removeFavorite', { hobbyId: hobby.id }) }}"
                                method="POST"
                                {{ stimulus_controller('favorites') }}
                                data-action="submit-confirm#onSubmit"
                        >

                            <div class="favorite_remove"
                                    {{ stimulus_target('favorites', 'icon') }}
                                    {{ stimulus_action('favorites', 'manageFavorite', 'click') }}>
                            </div>
                        </form>
                    {% elseif isFavorite == false %}
                        <form   action="{{ path('app_addFavorite', { hobbyId: hobby.id }) }}"
                                method="POST"
                                {{ stimulus_controller('favorites') }}>
                            <div class="favorite_add"
                                    {{ stimulus_target('favorites', 'icon') }}
                                    {{ stimulus_action('favorites', 'manageFavorite', 'click') }}>
                            </div>
                        </form>
                    {% else %}
                        weird
                    {% endif %}

                {% else %}
                    <div class="tooltip" {{ stimulus_controller('favorites') }}>
                        <div class="favorite_add"
                                {{ stimulus_action('favorites', 'notConnected', 'click') }}>
                        </div>
                        <span class="tooltiptext" {{ stimulus_target('favorites', 'tooltip') }}><a href="{{ path('app_login') }}">Log in</a><br/> to add it to your favorites!</span>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="hobby_card_bottom">
            <a href="#" class="hobby_card_bottom_button">
                See more
            </a>
            {% if hobby.website %}
                <a href="{{ hobby.website }}" target="_blank" class="hobby_card_bottom_button">
                    Visit website <i class="fa fa-external-link hobby_card_bottom_button_extlink_icon" aria-hidden="true"></i>
                </a>
            {% else %}
                <a class="hobby_card_bottom_button_nolink">
                    Visit website <i class="fa fa-external-link hobby_card_bottom_button_extlink_icon" aria-hidden="true"></i>
                </a>
            {% endif %}
            <a href="#" class="hobby_card_bottom_button">
                Ask for support
            </a>
        </div>
    </div>
</div>

templates/hobby/content.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {% include 'header/default.html.twig' %}
{% endblock %}

{% block content %}
    {% include 'header/hobbyFamilies.html.twig' %}

    <div class="categories_background" data-controller="categoriesfilter">
        {% if hobbies is not defined %}
            {% if hobby_categories is defined %}
                <div class="categories_search">
                    <input  data-action="keyup->categoriesfilter#categories_filter" data-categoriesfilter-target="filter" type="text" placeholder="Enter a sport: taekwondo, badminton..." class="categories_search_input">
                    <div class="search_icon"></div>
                </div>
                <div class="categories">
                    {% for hobby_category in hobby_categories | sort((a,b) => a.name <=> b.name) %}
                        <a data-categoriesfilter-target="category" class="category" href="{{ path('app_hobbiesKorea', { family_name: hobby_category.hobbyFamilies.name, category_name: hobby_category.name}) }}">
                            {{ hobby_category.name }}
                        </a>
                    {% endfor %}
                </div>

            {% endif %}
        {% endif %}
        {% if hobbies is defined %}
            <div class="category_title">
                {{ selected_category }}
            </div>
        {% endif %}
    </div>

    {% if hobbies is defined %}
    <div>
        {% for hobby in hobbies %}
            {% if loop.last %}
                <div class="hobbies_count">
                    <div class="hobbies_count_text">
                        {{ loop.length }} results
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="hobbies_results_area">
            <div class="hobbies_results">
                {% for hobby in hobbies %}
                    {% include 'hobby/_hobbyCard.html.twig' %}
                {% endfor %}
            </div>
            <div class="hobbies_map">
                <div class="map"
                        {{ stimulus_controller('map', {
                            latlong: coordinates,
                        }) }}
                        {{ stimulus_target('map', 'map') }}>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}